name: Download dove
description: Download dove
inputs:
  version:
    description: Dove version
    required: true
    default: "latest"
runs:
  using: "composite"
  steps:
#    - name: access
#      run: |
#        if [ ! "$RUNNER_OS" == "Windows" ]; then
#             sudo chown runner ${{ github.action_path }}/dove_download.sh && chmod +x ${{ github.action_path }}/dove_download.sh
#        fi
#      shell: bash
#    - run: echo ${{ github.action_path }}
#      shell: bash
#    - run: env
#      shell: bash
#    - run: echo $GITHUB_ACTION_PATH
#      shell: bash
    - run: ls -l $GITHUB_ACTION_PATH
      shell: bash
    - run: $GITHUB_ACTION_PATH/dove_download.sh
      shell: bash
#    - run: ls -l ${{ github.action_path }}
#      shell: bash
#    - run: $GITHUB_ACTION_PATH/dove_download.sh
#      shell: bash

