name: Download dove
description: Download dove
inputs:
  version:
    description: Dove version
    required: true
    default: "latest"
runs:
  using: "composite"
  steps:
    - name: access
      run: |
        if [ ! "$RUNNER_OS" == "Windows" ]; then
             sudo chown runner ${{ github.action_path }}/dove_download.sh && chmod +x ${{ github.action_path }}/dove_download.sh
        fi
      shell: bash
    - run: ${{ github.action_path }}/dove_download.sh ${{ inputs.version }}
      shell: bash

