name: My action
description: Download dove
inputs:
  version:
    description: Dove version
    required: true
    default: "latest"
runs:
  using: "composite"
  steps:
    - name: Cache
      uses: actions/cache@v2
      with:
        path: ~/.dove
        key: ${{ runner.os }}-dove
    - name: access
      run: sudo chown runner ${{ github.action_path }}dove_download.sh && chmod +x ${{ github.action_path }}/dove_download.sh
    - run: ls -l ${{ github.action_path }}
      shell: bash
    - run: echo "end"
      shell: bash
    - run: ${{ github.action_path }}/dove_download.sh ${{ inputs.version }}
      shell: bash

