name: My action
description: Download dove
inputs:
  version:
    description: Dove version
    required: true
    default: "latest"
runs:
  using: "composite"
  steps:
    - name: access
      run: sudo chown runner ${{ github.action_path }}/dove_download.sh && chmod +x ${{ github.action_path }}/dove_download.sh
      shell: bash
    - run: ls -l ${{ github.action_path }}
      shell: bash
    - run: echo "end"
      shell: bash
    - run: ${{ github.action_path }}/dove_download.sh ${{ inputs.version }}
      shell: bash

