name: tests
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v1

      - name: realpath
        run: realpath ./

      - name: ls
        run: ls

      - name: ls
        run: ls ../

      - name: ls
        run: ls ../../

      - name: run ubuntu
        run: cat ./dove_download.sh



