name: tests
on:
  pull_request:
  push:
    branches:
      - master

jobs:
#  ubuntu:
#    runs-on: ubuntu-latest
#    defaults:
#      run:
#        shell: bash
#
#    steps:
#      - uses: actions/checkout@v1
#      - name: access
#        run: sudo chown runner ./dove_download.sh && chmod +x ./dove_download.sh
#      - name: run on ubuntu
#        run: bash ./dove_download.sh
#      - name: ls
#        run: ls

  windows:
      runs-on: windows-latest
      defaults:
        run:
          shell: bash

      steps:
        - uses: actions/checkout@v1
        - name: run on windwows
          run: bash ./dove_download.sh
        - name: ls
          run: ls



