name: Test action
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.dove
          key: ${{ runner.os }}-dove
      - name: download latest version
        uses: vladimirovmm/dove_download_test@master
      - name: test
        run: dove -V
      - name: download 1.2.1 version
        uses: vladimirovmm/dove_download_test@master
        with:
          version: 1.2.1
      - name: test
        run: dove -V

  macos:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.dove
          key: ${{ runner.os }}-dove
      - name: download latest version
        uses: vladimirovmm/dove_download_test@master
      - name: test
        run: dove -V

  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.dove
          key: ${{ runner.os }}-dove
      - name: download latest version
        uses: vladimirovmm/dove_download_test@master
      - name: test
        run: dove -V
