name: Test action
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Dove
        uses: actions/dove_download@master

      - name: test
        run: dove -V
      - name: download 1.2.1 version
        run: bash ./dove_download.sh 1.2.1
      - name: test
        run: dove -V
#
#  macos:
#    runs-on: macos-latest
#    defaults:
#      run:
#        shell: bash
#    steps:
#      - name: Cache
#        uses: actions/cache@v2
#        with:
#          path: ~/.dove
#          key: ${{ runner.os }}-dov
#      - name: Checkout
#        uses: actions/checkout@v1
#      - name: access
#        run: sudo chown runner ./dove_download.sh && chmod +x ./dove_download.sh
#      - name: download latest version
#        run: bash ./dove_download.sh
#      - name: test
#        run: dove -V
#
#  windows:
#    runs-on: windows-latest
#    defaults:
#      run:
#        shell: bash
#    steps:
#      - name: Cache
#        uses: actions/cache@v2
#        with:
#          path: ~/.dove
#          key: ${{ runner.os }}-dove
#      - name: Checkout
#        uses: actions/checkout@v1
#      - name: download latest version
#        run: bash ./dove_download.sh
#      - name: test
#        run: dove -V
#
#
#
